name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm install -g semantic-release

      - run: |
          git config --global user.name "index-github-runner"
          git config --global user.email "runner@index.index.one"
          git remote set-url origin "https://x-access-token:${{ secrets.CI_TOKEN }}@github.com/${{ github.repository }}.git"

      - run: npx semantic-release || echo "Semantic release failed"
